name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment
        run: |
          # Создаем структуру для GitHub Pages
          mkdir -p public
          
          # Копируем основной контент
          cp -r frontend/* public/
          
          # Копируем в корень public
          cp frontend/templates/cart.html public/
          cp frontend/templates/admin.html public/
          
          # Проверяем наличие критичных файлов
          echo "Проверка файлов:"
          ls -la public/cart.html
          ls -la public/static/js/
          ls -la public/static/css/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
