name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Move files from frontend to root
        run: |
          mv frontend/* .
          mv frontend/.* . || true
          
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
