name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment
        run: |
          mkdir -p public
          cp -r frontend/* public/
          cp frontend/templates/cart.html public/
          cp frontend/templates/orders.html public/  # Добавлена эта строка
          
          # Создаем конфиг с базовым URL
          echo '{ "baseUrl": "/web-shop-2025/" }' > public/config.json

      - name: Verify files
        run: |
          ls -la public/static/css/
          ls -la public/static/js/
          ls -la public/  # Проверяем, что orders.html скопировался
          
          # Дополнительная проверка
          echo "Проверка наличия ключевых файлов:"
          [ -f public/orders.html ] && echo "orders.html найден" || echo "orders.html НЕ найден"
          [ -f public/cart.html ] && echo "cart.html найден" || echo "cart.html НЕ найден"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
