name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare files
        run: |
          # Копируем всё содержимое frontend в корень
          cp -r frontend/* .
          cp -r frontend/.[^.]* . || true  # Игнорируем ошибки для скрытых файлов

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
