name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment
        run: |
          # Создаем структуру как ожидает GitHub Pages
          mkdir -p public
          cp -r frontend/* public/
          
          # Проверяем наличие критичных файлов
          ls -la public/static/css/
          ls -la public/static/uploads/
          
          # Для отладки
          tree public -L 3

          mkdir -p public
          cp -r frontend/* public/
          ls -la public/static/css/admin.css
          ls -la public/static/js/admin.js

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
