name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to root
        run: |
          # Копируем всё содержимое frontend в корень
          cp -r frontend/* .
          
          # Копируем отдельно папку static (если нужно сохранить структуру)
          cp -r frontend/static .
          
          # Копируем скрытые файлы (если есть)
          cp -r frontend/.[^.]* . || true
          
          # Проверяем что скопировалось (для отладки)
          ls -R

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
