name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment structure
        run: |
          # Правильная структуру\а
          mkdir -p public
          cp -r frontend/* public/
          
          # Копируем статику с сохранением структуры
          mkdir -p public/static
          cp -r frontend/static/* public/static/
                
          # Проверяем структуру для отладки
          ls -R public

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'  # Указываем папку public как корень для Pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
