name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment
        run: |
          # Создаем структуру
          mkdir -p public
          
          # Копируем ВСЁ из frontend
          cp -r frontend/* public/
          
          # Явно копируем cart.html из templates в корень public
          cp frontend/templates/cart.html public/
          
          # Проверяем структуру (для отладки)
          echo "Содержимое public:"
          ls -la public/
          echo "Проверка cart.html в корне:"
          ls -la public/cart.html
          echo "Проверка cart.html в templates:"
          ls -la public/templates/cart.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
