name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare files
        run: |
          # Удаляем старые файлы (кроме .git и .github)
          find . -maxdepth 1 ! -name '.' ! -name '.git' ! -name '.github' -exec rm -rf {} +
          
          # Копируем только нужное из frontend
          cp -r frontend/* .
          cp -r frontend/static .
          
          # Переименовываем файлы с кириллицей
          rename 's/русские_символы/english_name/' static/uploads/* || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - uses: actions/deploy-pages@v4
